services:
  umami:
    build:
      context: .
      args:
        DATABASE_TYPE: postgresql
        OPENAI_API_KEY: "yC8cI1hwNRm8WbXTkPOdgnt4"
    image: umami:custom
    pull_policy: never
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      OPENAI_API_KEY: "yC8cI1hwNRm8WbXTkPOdgnt4"
      APP_SECRET: change-me-to-a-strong-random-string
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  umami-db-data: